[package]
name = "horologe"
version = "1.0.0"
authors = ["Michael Dippery <michael@monkey-robot.com>"]
description = "Earth has 4 corner simultaneous 4-day time cube within single rotation."
#readme = "README.md"
#documentation = "https://docs.rs/horologe"
#repository = "https://github.com/mdippery/horologe"
#homepage
license = "MIT"
keywords = ["calendar", "date", "time", "timezone"]
categories = ["date-and-time"]
edition = "2024"
#rust-version

[features]
age = []
relative-age = ["age"]

[dependencies]
